"""Capture real request/response evidence into `examples/`.

Everything in `examples/` is generated by running the actual pipeline against the
mock GoHighLevel server and recording what really crossed the wire. Nothing is
hand-written, so the files cannot drift from the code and cannot be a flattering
fiction. Regenerate with:

    python scripts/capture_examples.py

The `demo` CI job runs the same code path on every push, so a change that would
invalidate these examples fails the build.
"""

from __future__ import annotations

import asyncio
import json
import pathlib
import sys
import tempfile
from typing import Any

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))
sys.path.insert(0, str(REPO))

import httpx  # noqa: E402
from mock.ghl_mock import server as mock  # noqa: E402

from leadops.config import Settings  # noqa: E402
from leadops.ghl.client import GHLClient  # noqa: E402
from leadops.ghl.mapping import GHLMapping  # noqa: E402
from leadops.logging_setup import configure_logging  # noqa: E402
from leadops.pipeline import process_lead  # noqa: E402
from leadops.reliability.retry import RetryPolicy  # noqa: E402
from leadops.routing.rules import RoutingTable  # noqa: E402
from leadops.storage import (  # noqa: E402
    create_all,
    init_engine,
    repo,  # noqa: E402
    session_scope,
)
from leadops.storage.db import reset_for_tests  # noqa: E402

# Headers worth recording: the ones that show the integration contract, not the
# ones httpx adds for transport.
INTERESTING_HEADERS = frozenset(
    {"authorization", "version", "content-type", "accept", "x-correlation-id"}
)

OUT = REPO / "examples"
FIXTURES = REPO / "n8n" / "fixtures"


def write(name: str, payload: Any, note: str) -> None:
    OUT.mkdir(exist_ok=True)
    document = {"_note": note, **payload} if isinstance(payload, dict) else payload
    (OUT / name).write_text(json.dumps(document, indent=2, default=str) + "\n", encoding="utf-8")
    print(f"  wrote examples/{name}")


async def main() -> int:
    configure_logging("ERROR", "text")
    workdir = tempfile.mkdtemp(prefix="leadops-capture-")

    settings = Settings(
        database_url=f"sqlite+aiosqlite:///{workdir}/capture.sqlite3",
        ghl_base_url="http://ghl.mock",
        ghl_access_token="capture_token_not_a_real_secret",
        ghl_location_id="loc_DEMO0000000000000000",
        ghl_pipeline_id="pipe_DEMO000000000000000",
        ai_provider="deterministic",
        ghl_backoff_base_seconds=0.0,
        ghl_backoff_max_seconds=0.0,
        routing_config_path=str(REPO / "config" / "routing.yml"),
        ghl_mapping_path=str(REPO / "config" / "ghl-mapping.json"),
    )
    await reset_for_tests()
    init_engine(settings.database_url)
    await create_all()
    mock.state.reset()

    mapping = GHLMapping.load(settings.ghl_mapping_path)
    table = RoutingTable.load(settings.routing_config_path)

    # Record every outbound request body as it is actually sent.
    captured: list[dict] = []

    class Recording(httpx.AsyncBaseTransport):
        def __init__(self, inner: httpx.AsyncBaseTransport) -> None:
            self.inner = inner

        async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
            response = await self.inner.handle_async_request(request)
            await response.aread()
            body = None
            if request.content:
                try:
                    body = json.loads(request.content)
                except ValueError:
                    body = None
            try:
                parsed = json.loads(response.content) if response.content else None
            except ValueError:
                parsed = None
            captured.append(
                {
                    "request": {
                        "method": request.method,
                        "url": str(request.url),
                        "headers": {
                            key: ("Bearer <redacted>" if key.lower() == "authorization" else value)
                            for key, value in request.headers.items()
                            if key.lower() in INTERESTING_HEADERS
                        },
                        "body": body,
                    },
                    "response": {"status": response.status_code, "body": parsed},
                }
            )
            return response

    def client() -> GHLClient:
        return GHLClient(
            base_url="http://ghl.mock",
            access_token=settings.ghl_access_token,
            location_id=settings.ghl_location_id,
            client=httpx.AsyncClient(
                transport=Recording(httpx.ASGITransport(app=mock.app)),
                base_url="http://ghl.mock",
                timeout=10.0,
            ),
            policy=RetryPolicy(max_attempts=3, base_seconds=0.0, max_seconds=0.0),
        )

    fixture = json.loads((FIXTURES / "website-lead-emergency.json").read_text(encoding="utf-8"))

    print("Capturing a real run against the mock GoHighLevel API...")
    async with session_scope() as session:
        result = await process_lead(
            source="website",
            payload=fixture,
            headers={},
            settings=settings,
            session=session,
            ghl=client(),
            mapping=mapping,
            table=table,
        )

    write(
        "01-incoming-webhook.json",
        fixture,
        "The raw website form post, exactly as it arrives at POST /webhooks/leads/website.",
    )
    write(
        "02-normalized-lead.json",
        result.lead.model_dump(mode="json"),
        "After normalization. Note the lowercased email and the E.164 phone - this is "
        "what makes GoHighLevel's own duplicate matching work.",
    )
    write(
        "03-ai-qualification.json",
        result.qualification.model_dump(mode="json"),
        "Structured qualification, schema-validated and clamped. `provider` is "
        "'deterministic' here because the demo runs offline; `degraded` false means "
        "this was the configured provider, not a fallback.",
    )
    write(
        "04-routing-decision.json",
        result.routing.model_dump(mode="json"),
        "Produced by deterministic rules from config/routing.yml - never by the model. "
        "`reason` is carried through so the audit log explains itself.",
    )
    write(
        "05-ghl-api-calls.json",
        {"calls": captured},
        "Every request and response that actually crossed the wire during this one "
        "lead, captured at the transport layer. Bearer token redacted.",
    )
    write(
        "06-webhook-response.json",
        result.public_response(),
        "What the webhook caller (n8n) receives. n8n branches on `status` and `routing` "
        "and needs nothing else.",
    )

    async with session_scope() as session:
        audit = await repo.audit_for_event(session, result.event_id)
        calls = await repo.provider_calls_for_event(session, result.event_id)
        write(
            "07-audit-trail.json",
            {
                "event_id": result.event_id,
                "correlation_id": result.correlation_id,
                "steps": [
                    {"step": a.step, "ok": a.ok, "duration_ms": a.duration_ms, "detail": a.detail}
                    for a in audit
                ],
                "provider_calls": [
                    {
                        "provider": c.provider,
                        "operation": c.operation,
                        "ok": c.ok,
                        "attempts": c.attempts,
                        "duration_ms": round(c.duration_ms, 1),
                    }
                    for c in calls
                ],
            },
            "What GET /admin/events/{id} returns: every step with timings and every "
            "outbound call with attempt counts. This is the troubleshooting surface.",
        )

    # A second delivery of the same event, to capture the duplicate response.
    async with session_scope() as session:
        duplicate = await process_lead(
            source="website",
            payload=fixture,
            headers={},
            settings=settings,
            session=session,
            ghl=client(),
            mapping=mapping,
            table=table,
        )
    write(
        "08-duplicate-delivery.json",
        {
            "response": duplicate.public_response(),
            "ghl_contacts_after_two_deliveries": len(mock.state.contacts),
            "ghl_contact_upsert_calls": mock.state.call_counts["contacts.upsert"],
        },
        "The same webhook delivered twice. Status is 'duplicate', the original "
        "contact id is returned, and GoHighLevel was called once - not twice.",
    )

    await reset_for_tests()
    print(f"\nDone. {len(captured)} GoHighLevel calls captured.")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
